
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/semogong
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'dlwogns1205@gmail.com'
    password: 'mrah qxxf okfz fwjf'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging.level:
  org.hibernate.SQL: debug




